/**
 * 服务端翻译包合并清单
 *
 * ⚠️  AUTO-GENERATED by scripts/generate-i18n-bundles.ts — DO NOT EDIT MANUALLY
 * @module core/i18n/bundles
 */

import arAuth from "./locales/ar/auth.json";
import arCommon from "./locales/ar/common.json";
import arCrm from "./locales/ar/crm.json";
import arLearning from "./locales/ar/learning.json";
import arMembership from "./locales/ar/membership.json";
import arPayment from "./locales/ar/payment.json";
import arProcurement from "./locales/ar/procurement.json";
import arServices from "./locales/ar/services.json";
import arShowroom from "./locales/ar/showroom.json";
import arSupplier from "./locales/ar/supplier.json";
import arTraining from "./locales/ar/training.json";

import enAuth from "./locales/en/auth.json";
import enCommon from "./locales/en/common.json";
import enCrm from "./locales/en/crm.json";
import enLearning from "./locales/en/learning.json";
import enMembership from "./locales/en/membership.json";
import enPayment from "./locales/en/payment.json";
import enProcurement from "./locales/en/procurement.json";
import enServices from "./locales/en/services.json";
import enShowroom from "./locales/en/showroom.json";
import enSupplier from "./locales/en/supplier.json";
import enTraining from "./locales/en/training.json";

import esAuth from "./locales/es/auth.json";
import esCommon from "./locales/es/common.json";
import esCrm from "./locales/es/crm.json";
import esLearning from "./locales/es/learning.json";
import esMembership from "./locales/es/membership.json";
import esPayment from "./locales/es/payment.json";
import esProcurement from "./locales/es/procurement.json";
import esServices from "./locales/es/services.json";
import esShowroom from "./locales/es/showroom.json";
import esSupplier from "./locales/es/supplier.json";
import esTraining from "./locales/es/training.json";

import frAuth from "./locales/fr/auth.json";
import frCommon from "./locales/fr/common.json";
import frCrm from "./locales/fr/crm.json";
import frLearning from "./locales/fr/learning.json";
import frMembership from "./locales/fr/membership.json";
import frPayment from "./locales/fr/payment.json";
import frProcurement from "./locales/fr/procurement.json";
import frServices from "./locales/fr/services.json";
import frShowroom from "./locales/fr/showroom.json";
import frSupplier from "./locales/fr/supplier.json";
import frTraining from "./locales/fr/training.json";

import ruAuth from "./locales/ru/auth.json";
import ruCommon from "./locales/ru/common.json";
import ruCrm from "./locales/ru/crm.json";
import ruLearning from "./locales/ru/learning.json";
import ruMembership from "./locales/ru/membership.json";
import ruPayment from "./locales/ru/payment.json";
import ruProcurement from "./locales/ru/procurement.json";
import ruServices from "./locales/ru/services.json";
import ruShowroom from "./locales/ru/showroom.json";
import ruSupplier from "./locales/ru/supplier.json";
import ruTraining from "./locales/ru/training.json";

import zhAuth from "./locales/zh/auth.json";
import zhCommon from "./locales/zh/common.json";
import zhCrm from "./locales/zh/crm.json";
import zhLearning from "./locales/zh/learning.json";
import zhMembership from "./locales/zh/membership.json";
import zhPayment from "./locales/zh/payment.json";
import zhProcurement from "./locales/zh/procurement.json";
import zhServices from "./locales/zh/services.json";
import zhShowroom from "./locales/zh/showroom.json";
import zhSupplier from "./locales/zh/supplier.json";
import zhTraining from "./locales/zh/training.json";

const mergeNamespaces = (...modules: Record<string, unknown>[]): Record<string, string> => {
  const result: Record<string, string> = {};
  for (const m of modules) {
    if (typeof m === "object" && m !== null && "default" in m) {
      Object.assign(result, (m as { default: Record<string, string> }).default);
    } else {
      Object.assign(result, m);
    }
  }
  return result;
};

export const SERVER_BUNDLES: Record<string, { translation: Record<string, string> }> = {
  ar: { translation: mergeNamespaces(arAuth, arCommon, arCrm, arLearning, arMembership, arPayment, arProcurement, arServices, arShowroom, arSupplier, arTraining) },
  en: { translation: mergeNamespaces(enAuth, enCommon, enCrm, enLearning, enMembership, enPayment, enProcurement, enServices, enShowroom, enSupplier, enTraining) },
  es: { translation: mergeNamespaces(esAuth, esCommon, esCrm, esLearning, esMembership, esPayment, esProcurement, esServices, esShowroom, esSupplier, esTraining) },
  fr: { translation: mergeNamespaces(frAuth, frCommon, frCrm, frLearning, frMembership, frPayment, frProcurement, frServices, frShowroom, frSupplier, frTraining) },
  ru: { translation: mergeNamespaces(ruAuth, ruCommon, ruCrm, ruLearning, ruMembership, ruPayment, ruProcurement, ruServices, ruShowroom, ruSupplier, ruTraining) },
  zh: { translation: mergeNamespaces(zhAuth, zhCommon, zhCrm, zhLearning, zhMembership, zhPayment, zhProcurement, zhServices, zhShowroom, zhSupplier, zhTraining) },
};

/** 支持的完整语言代码列表 */
export const SUPPORTED_LOCALE_CODES = ["ar", "en", "es", "fr", "ru", "zh"] as const;

/** 语言类型 */
export type { Locale } from "./types";

/** 获取语言书写方向 */
export function getLocaleDir(locale: string): "ltr" | "rtl" {
  return locale === "ar" ? "rtl" : "ltr";
}
